print("         \\|||/")
print("         (o o)")
print("|~~~~oo0~~(_)~~~~~~~~|")
print("| Please             |")
print("| don't feed the     |")
print("| TROLLS !           |")
print("'~~~~~~~~~~~~0oo~~~~~'")
print("       |___|___|  ")
print("        | | | |   ")
print("        oo0 0oo")
